name: Build Userscript

on:
    push:
        branches: [main]

jobs:
    deploy:
        if: startsWith(github.event.head_commit.message, 'v')
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Setup Node
              uses: actions/setup-node@v2
              with:
                  node-version: "16"
            #         cache: 'npm'

            - name: Install node packages
              run: npm install

            - name: Run build
              run: npm run build

            - name: Push changes
              run: |
                  git config --global user.name ${{ secrets.USER_NAME }}
                  git config --global user.email ${{ secrets.USER_EMAIL }}
                  git commit -am "${{ github.event.head_commit.message }}" --allow-empty
                  git push origin

            - name: Create tag
              id: tag_version
              uses: mathieudutour/github-tag-action@v6.0
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  custom_tag: ${{ github.event.head_commit.message }}

            - name: Create release
              uses: ncipollo/release-action@v1
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  tag: ${{ steps.tag_version.outputs.new_tag }}
                  name: Release ${{ steps.tag_version.outputs.new_tag }}
