name: Build Userscript

on:
    push:
        tags:
            - "v*"

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Setup Node
              uses: actions/setup-node@v2
              with:
                  node-version: "16"
            #         cache: 'npm'
            - run: npm install
            - run: npm run build
            - run: |
                  git config --global user.name ${{ secrets.USER_NAME }}
                  git config --global user.email ${{ secrets.USER_EMAIL }}
                  git commit -am "${{ github.ref_name }}" --allow-empty
                  git push origin
            - uses: ncipollo/release-action@v1
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
